{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-runtime-attribute",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.1.aar",
          "url": "hikage-runtime-attribute-1.1.1.aar",
          "size": 113427,
          "sha512": "640c6d94e9536195dfd010a427bbc83b71687b232db2495abc2d798a0923e3c0b6ad81653f292fa4a3b0bf6de2362c5baafeccbdbb454db73a8b1441e7c8a012",
          "sha256": "34344924b1c1b0471e6f40ceffbe0750ca4103d5edcae2519fc0d3954b6e3bff",
          "sha1": "acb6b120d00c05c8ff5174b5f85aa5b425d3b3b7",
          "md5": "b98a3fd99f34c4c213663e6012a7073f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "6.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "android-bom",
          "version": {
            "requires": "1.1.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.1.aar",
          "url": "hikage-runtime-attribute-1.1.1.aar",
          "size": 113427,
          "sha512": "640c6d94e9536195dfd010a427bbc83b71687b232db2495abc2d798a0923e3c0b6ad81653f292fa4a3b0bf6de2362c5baafeccbdbb454db73a8b1441e7c8a012",
          "sha256": "34344924b1c1b0471e6f40ceffbe0750ca4103d5edcae2519fc0d3954b6e3bff",
          "sha1": "acb6b120d00c05c8ff5174b5f85aa5b425d3b3b7",
          "md5": "b98a3fd99f34c4c213663e6012a7073f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.1-sources.jar",
          "url": "hikage-runtime-attribute-1.1.1-sources.jar",
          "size": 44282,
          "sha512": "db57bb0a73abd154f3a2b4d3d74ff13b9775b3c942a208e3545a8baae107f821d00c8adf48c980d384bf365f0ca1c6a1c962408380052dc3a49b5d4c64f65701",
          "sha256": "75d088f9bd19ae275b31f80d583526e6c5b40fbe79013a512c3a61f8d2291154",
          "sha1": "86863aa48b4b4eb7a8c5bc1cf96d864d9246c525",
          "md5": "27cdeec7a44d150d01a7622051c4c043"
        }
      ]
    }
  ]
}
