{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hikage-gradle-plugin-1.0.0.jar",
          "url": "hikage-gradle-plugin-1.0.0.jar",
          "size": 59650,
          "sha512": "61c438863893c51c2b5b3d7fa46e67168a96d1f1ea00ed8dc5a98b3089c04f423b55e652a8a5e065161175d958ca70ae18359f20f9789792fa1e8f03fe3f8a0a",
          "sha256": "57543b27bce4689132528f86a6712fb8f0d733af36b6874ec6eb28326b29f716",
          "sha1": "cbd6c20a65d6a96270d564e3ca188657d7e0ca14",
          "md5": "e75158ed0470df6b48ad1bfa55556e2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.6"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-gradle-plugin-1.0.0.jar",
          "url": "hikage-gradle-plugin-1.0.0.jar",
          "size": 59650,
          "sha512": "61c438863893c51c2b5b3d7fa46e67168a96d1f1ea00ed8dc5a98b3089c04f423b55e652a8a5e065161175d958ca70ae18359f20f9789792fa1e8f03fe3f8a0a",
          "sha256": "57543b27bce4689132528f86a6712fb8f0d733af36b6874ec6eb28326b29f716",
          "sha1": "cbd6c20a65d6a96270d564e3ca188657d7e0ca14",
          "md5": "e75158ed0470df6b48ad1bfa55556e2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-gradle-plugin-1.0.0-sources.jar",
          "url": "hikage-gradle-plugin-1.0.0-sources.jar",
          "size": 13551,
          "sha512": "4d65862806799bd7791799c99ac3fd426cc73cf821a4f1f7e1544cda2b71f34d634e40fdc1329869ffa7d25dad19c2149ab5c408d643d8c3f9c687fd89d12830",
          "sha256": "3f6b58f8610696825f04262bfc83496a0f7cde992be34d79c72aa1a22ac46945",
          "sha1": "ee75e8cc1bb518527f812183b77635d4da6d06b7",
          "md5": "73d931995fdab7719c74c35b8c28d789"
        }
      ]
    }
  ]
}
