{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component-adapter",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-adapter-1.1.2.aar",
          "url": "ui-component-adapter-1.1.2.aar",
          "size": 164729,
          "sha512": "c29e426b7fc8be7b20cc04c66b88892bd303ba8425f092142b01b68280f89322d893729633be3c3a3af3a9c1a197dd48f0b2d4be4b0fa7dc3e0b400f230feba6",
          "sha256": "5a2c970050e92fb8a6597dc4ce9db783bdb41793ecdcc2639be2baf7201d073c",
          "sha1": "1d33897757ab5de95f49f696fe38a2df6fcd28da",
          "md5": "85037fa219c8d1ba549969c57c41627d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-adapter-1.1.2.aar",
          "url": "ui-component-adapter-1.1.2.aar",
          "size": 164729,
          "sha512": "c29e426b7fc8be7b20cc04c66b88892bd303ba8425f092142b01b68280f89322d893729633be3c3a3af3a9c1a197dd48f0b2d4be4b0fa7dc3e0b400f230feba6",
          "sha256": "5a2c970050e92fb8a6597dc4ce9db783bdb41793ecdcc2639be2baf7201d073c",
          "sha1": "1d33897757ab5de95f49f696fe38a2df6fcd28da",
          "md5": "85037fa219c8d1ba549969c57c41627d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-adapter-1.1.2-sources.jar",
          "url": "ui-component-adapter-1.1.2-sources.jar",
          "size": 57623,
          "sha512": "08fae81e32630980cf44cf3a365c0e49e92dd925147b9c0c1bfe29eac79ad351792ba734f769a19fa59ef43fdbb699b65f45de17cda715d1489d8139954507e5",
          "sha256": "099cb9bc710f1843ecc013f82cef65ffdb20ef75f0de884cfe6c00e2e870ab0b",
          "sha1": "6e42c1d364f37c5bafaf71ca60328703baab698f",
          "md5": "9b0fcfc092cdd3c4ee37e32fa632c105"
        }
      ]
    }
  ]
}
