{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-metadata-1.0.3.jar",
          "url": "compose-extension-1.0.3.jar",
          "size": 10404,
          "sha512": "7b8bd494d1a24e24112129f7c8b77c13b8257c1cd6c7e42a46c94bba17e12e28a7bdcde20fa1a0a44d2601455ef9c7d33c128927a2f856cad58b917dccd6d1fe",
          "sha256": "016f0a27d0547c3459a1da26230ac593b049008f6f27dd9e7573a476b7b8c966",
          "sha1": "8f5d1504d257965034e731ce7e7c5121617a4457",
          "md5": "c49ff6c49e86684df29a3190e4aeae40"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-extension-kotlin-1.0.3-sources.jar",
          "url": "compose-extension-1.0.3-sources.jar",
          "size": 20494,
          "sha512": "73221122c34ca9c6f2e32c43fe692aaa028db7d35193b578cfbe8b8eb67e72e557459db06b4b1c2efd1d7194ae337c2301534841958b93747fa40f43a6f43eff",
          "sha256": "92a64c810f3153991036f676e76b1e410d0c385ab8bc4db011d29813ac9bbb7f",
          "sha1": "499842f3fb88b2951142989ccbb75aeef31726c6",
          "md5": "21b7804e330873b03ec0a2c95092a65f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.3/compose-extension-android-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.3/compose-extension-android-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-extension-android/1.0.3/compose-extension-android-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.3/compose-extension-desktop-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.3/compose-extension-desktop-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-extension-desktop/1.0.3/compose-extension-desktop-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.3/compose-extension-iosarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.3/compose-extension-iosarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.3/compose-extension-iosarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosarm64/1.0.3/compose-extension-iosarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.3/compose-extension-iossimulatorarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.3/compose-extension-iossimulatorarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.3/compose-extension-iossimulatorarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iossimulatorarm64/1.0.3/compose-extension-iossimulatorarm64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.3/compose-extension-iosx64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.3/compose-extension-iosx64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.3/compose-extension-iosx64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-extension-iosx64/1.0.3/compose-extension-iosx64-1.0.3.module",
        "group": "com.highcapable.betterandroid",
        "module": "compose-extension-iosx64",
        "version": "1.0.3"
      }
    }
  ]
}
