{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-runtime-attribute",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.0.aar",
          "url": "hikage-runtime-attribute-1.1.0.aar",
          "size": 113372,
          "sha512": "0318c261f83c312fd4dfb30d8016d2e68869b94d28375bd672ea7642b793d49c54e813060658e6a548566d4fefa1471ec0399a38fd4424b95e9179f7403ccd40",
          "sha256": "a328ec62a3bf095874f10bb6f1071990f28f364c166b04f90ae9989c3e422e77",
          "sha1": "c34fb20a3eb4d01e46ec1efec75c1d1e23a59368",
          "md5": "21f0d524ff8bb12edf5cdb9095371681"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "6.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "android-bom",
          "version": {
            "requires": "1.1.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.0.aar",
          "url": "hikage-runtime-attribute-1.1.0.aar",
          "size": 113372,
          "sha512": "0318c261f83c312fd4dfb30d8016d2e68869b94d28375bd672ea7642b793d49c54e813060658e6a548566d4fefa1471ec0399a38fd4424b95e9179f7403ccd40",
          "sha256": "a328ec62a3bf095874f10bb6f1071990f28f364c166b04f90ae9989c3e422e77",
          "sha1": "c34fb20a3eb4d01e46ec1efec75c1d1e23a59368",
          "md5": "21f0d524ff8bb12edf5cdb9095371681"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-runtime-attribute-1.1.0-sources.jar",
          "url": "hikage-runtime-attribute-1.1.0-sources.jar",
          "size": 44248,
          "sha512": "2a2a95650de3d51e0fdc130e22c811185010f2b41869adaf4cc0840ed03caf490af6c4471027d2454b2646a49f36f6f5b61dd5b5593da362f0548e99c387e620",
          "sha256": "fb5f2a0fdafcad64a89fe22612fdf008e31ff87169412ef98e22de2fc2922c70",
          "sha1": "14433c7f5ae6d323d376a606676a719194280421",
          "md5": "3aecc0a7223865e352b4b84411645ae0"
        }
      ]
    }
  ]
}
