{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "system-extension",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.1.0.aar",
          "url": "system-extension-1.1.0.aar",
          "size": 146508,
          "sha512": "4768cfd4bd51e8e9ef1465e30d708d640b20d21c7d02f5483cd8247245961bf62fdb1b3f356c72238160f003a6ada1136eeb81cc88a1c511f12038f275b0bc44",
          "sha256": "b5a084921038f973fe64472493a393f8b6a1442342921a032ec3b4e522a9be5d",
          "sha1": "2f0805ab463e9376764e7387a96344030e53f9fa",
          "md5": "1bd690cbb45951de5c3acb8b7d554882"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "system-extension-1.1.0.aar",
          "url": "system-extension-1.1.0.aar",
          "size": 146508,
          "sha512": "4768cfd4bd51e8e9ef1465e30d708d640b20d21c7d02f5483cd8247245961bf62fdb1b3f356c72238160f003a6ada1136eeb81cc88a1c511f12038f275b0bc44",
          "sha256": "b5a084921038f973fe64472493a393f8b6a1442342921a032ec3b4e522a9be5d",
          "sha1": "2f0805ab463e9376764e7387a96344030e53f9fa",
          "md5": "1bd690cbb45951de5c3acb8b7d554882"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "system-extension-1.1.0-sources.jar",
          "url": "system-extension-1.1.0-sources.jar",
          "size": 21247,
          "sha512": "203d4279b205cc00de475714b4d903777f40152cc7d0c1bfd9b3bfce3e22db134545ce884ab00c239dd0f54e670a77ddf62a0414c8647d5c29121d96cdbfe462",
          "sha256": "b4fcff948b447e48d8c7502a7d074e971f839b5ac04c5887f4048f063375afa7",
          "sha1": "c8a1441e06fd9f4f88f4ab322a61f0cb9995798b",
          "md5": "d93aaa7976567fd307fdfe04cc15293c"
        }
      ]
    }
  ]
}
