{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.kavaref",
    "module": "kavaref-bom",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    }
  ]
}
