{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-core",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-widget-foundation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.1.1.aar",
          "url": "hikage-core-1.1.1.aar",
          "size": 237481,
          "sha512": "be30197e5973a52988a0bf7ecf06282540078d99dd7799c3b91bc09561976a8f592085c91f1ba1f4a3efa90c9d9f159f53fc39f441ae1ec084b97188a0027721",
          "sha256": "1d904f29def9d0462b25a9b7714b4d96aa31ff06b22e982f5f3796a78d976068",
          "sha1": "a0c0b1fbf6a686abfa1b632205366d0181b2aec1",
          "md5": "4bd5c8da0d3ba130ae5d664a4273b56d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "android-bom",
          "version": {
            "requires": "1.1.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.highcapable.hikage",
          "module": "hikage-widget-foundation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hikage-core-1.1.1.aar",
          "url": "hikage-core-1.1.1.aar",
          "size": 237481,
          "sha512": "be30197e5973a52988a0bf7ecf06282540078d99dd7799c3b91bc09561976a8f592085c91f1ba1f4a3efa90c9d9f159f53fc39f441ae1ec084b97188a0027721",
          "sha256": "1d904f29def9d0462b25a9b7714b4d96aa31ff06b22e982f5f3796a78d976068",
          "sha1": "a0c0b1fbf6a686abfa1b632205366d0181b2aec1",
          "md5": "4bd5c8da0d3ba130ae5d664a4273b56d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-core-1.1.1-sources.jar",
          "url": "hikage-core-1.1.1-sources.jar",
          "size": 47458,
          "sha512": "18b146ace46b2d8d994973a6df80b7e01977dbbef70002b05e19f580a9cedd4c6ba2272f83c76a34f8d691d0fef238c496d773073a189b2eb749c0639637361f",
          "sha256": "b6c777188cf73d276fb6529e1bd7039ec2c9513433dc053d969fffaa8ce5aa4d",
          "sha1": "c073f2d9cc566297b6f914744301944444914efe",
          "md5": "fe828fd354790a6ce0a6ca3cdaacbafc"
        }
      ]
    }
  ]
}
