{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.hikage",
    "module": "hikage-widget-androidx",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hikage-widget-androidx-1.1.1.jar",
          "url": "hikage-widget-androidx-1.1.1.jar",
          "size": 5289,
          "sha512": "dc694b95f6da26388de4b3b5636df012893afbb32cea4293303be09f34b46790cb1f16db31f78ea5f900bd71ad6a8cba8395c1980956f6a150e9c9e52dca8074",
          "sha256": "e9534d2829b90e6c9f2e0c99ab3f0b3ab7b4db72fd4fd298840920ec7fe7e9a8",
          "sha1": "4d80f1f7dc6bd4040fadd98a72e56ebf955b0291",
          "md5": "c0a3db22cf324db65c68d11e6b9b4e35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-widget-androidx-1.1.1.jar",
          "url": "hikage-widget-androidx-1.1.1.jar",
          "size": 5289,
          "sha512": "dc694b95f6da26388de4b3b5636df012893afbb32cea4293303be09f34b46790cb1f16db31f78ea5f900bd71ad6a8cba8395c1980956f6a150e9c9e52dca8074",
          "sha256": "e9534d2829b90e6c9f2e0c99ab3f0b3ab7b4db72fd4fd298840920ec7fe7e9a8",
          "sha1": "4d80f1f7dc6bd4040fadd98a72e56ebf955b0291",
          "md5": "c0a3db22cf324db65c68d11e6b9b4e35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hikage-widget-androidx-1.1.1-sources.jar",
          "url": "hikage-widget-androidx-1.1.1-sources.jar",
          "size": 5289,
          "sha512": "dc694b95f6da26388de4b3b5636df012893afbb32cea4293303be09f34b46790cb1f16db31f78ea5f900bd71ad6a8cba8395c1980956f6a150e9c9e52dca8074",
          "sha256": "e9534d2829b90e6c9f2e0c99ab3f0b3ab7b4db72fd4fd298840920ec7fe7e9a8",
          "sha1": "4d80f1f7dc6bd4040fadd98a72e56ebf955b0291",
          "md5": "c0a3db22cf324db65c68d11e6b9b4e35"
        }
      ]
    }
  ]
}
