{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.3/compose-extension-1.0.3.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-iosArm64Main-1.0.3.klib",
          "url": "compose-extension-iosarm64-1.0.3.klib",
          "size": 63802,
          "sha512": "f8402c3fdbf04d10ae5b56d5cd3d9e29d80643d8e61d221057c8b64bd602a52d4d5253f3434fc5796a644f4c82e06f5122de303f293a0fb3d6d2d516071e66fe",
          "sha256": "f6bcbf68aafd179700a40105fc1db0550279b382382b29a147a8a6e05617105a",
          "sha1": "dd679458cf5eb8341deccb079737cb9fcab68eab",
          "md5": "e3d535f942f839188c76b96498fd53d5"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-extension-iosarm64-1.0.3-sources.jar",
          "url": "compose-extension-iosarm64-1.0.3-sources.jar",
          "size": 20494,
          "sha512": "3e72297d8bf830de2963f60855fcecfbcc15ad0df1cd3560747a4512891d3b2ec6972573a5f7260d69f715665cb098e14d28b8e71338ad37c911db49c47ea411",
          "sha256": "c9d23989ac36b68527a6a3b8f89bcdb71f7310d486a2af72fd7dd45f9f94998d",
          "sha1": "997fb5b4819315cdb2c6fc47dc63f01795b6b5e9",
          "md5": "66416a7d8149e26def21ae7934be02af"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-1.0.3.kotlin_resources.zip",
          "url": "compose-extension-iosarm64-1.0.3-kotlin_resources.kotlin_resources.zip",
          "size": 382,
          "sha512": "9672e68e9bae1f75e43d969165295795989c1757a22815b1cf14fff2557558e78023fba57c58f06baacafdc764b3d2e3c86a3f05f4b2123d44b4fb36a6491606",
          "sha256": "e7252a06a9d6c82b6aa071db87c7645a9d153efbcaf219257ddd883e85424e00",
          "sha1": "da52456871e5349a2585e10e2a0b88d458199b72",
          "md5": "1dd3f1fdd256e1248ca804924bb78fcc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-iosarm64-1.0.3-metadata.jar",
          "url": "compose-extension-iosarm64-1.0.3-metadata.jar",
          "size": 4800,
          "sha512": "d121722888b49376a2b4f7021ae80e8e21f4d0bdf229d20c7ca5663cc2065e0763f362bc72905cc64ef2a35c73be6f4070302591d778d10e021225ef0928bb48",
          "sha256": "70b4f2867b32bc92b1452c59fedf0713be8dfecf87e198ee13196c7db137956d",
          "sha1": "b6e13b8cb66e057670dd3514520abecff4af2727",
          "md5": "df3196d737cdb0cda69487b74ea73851"
        }
      ]
    }
  ]
}
