{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-multiplatform/0.1.1/compose-multiplatform-0.1.1.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-multiplatform",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform.aar",
          "url": "compose-multiplatform-android-0.1.1.aar",
          "size": 18107,
          "sha512": "701f8d5a2f3de67b7243d2d0a9d44808c176f4f31c79ffa0df3a538d893d28c5c082bf6a013c2c252b1d184eaec61db048add0956b81d43219042f51c804b339",
          "sha256": "c6c297bf0b6fdff0500f78ce3ff6a637fafc45ad99df2210255494dff4b16b77",
          "sha1": "5dec9362bab25781c0b88368ad94eaee46049469",
          "md5": "c2ce4e44b496538d3bb3f53ad0557b3f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-component",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform.aar",
          "url": "compose-multiplatform-android-0.1.1.aar",
          "size": 18107,
          "sha512": "701f8d5a2f3de67b7243d2d0a9d44808c176f4f31c79ffa0df3a538d893d28c5c082bf6a013c2c252b1d184eaec61db048add0956b81d43219042f51c804b339",
          "sha256": "c6c297bf0b6fdff0500f78ce3ff6a637fafc45ad99df2210255494dff4b16b77",
          "sha1": "5dec9362bab25781c0b88368ad94eaee46049469",
          "md5": "c2ce4e44b496538d3bb3f53ad0557b3f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "compose-multiplatform-android-0.1.1-sources.jar",
          "url": "compose-multiplatform-android-0.1.1-sources.jar",
          "size": 13165,
          "sha512": "287e189c317966786341cfe0ffb96cf0278d3db78e00235e78c6ed08fc64e34b3985a339ce81d97e9c9e3fb7aa7b1e08e6486f0e4749e5400314876dc712505f",
          "sha256": "7386e258f2a535ed6484d23005f9b975b8333a45788902ca5fdd068daa8d3210",
          "sha1": "ee2d314d4485982b8f7763a3a4806829edfddea9",
          "md5": "a9eb5bb9ebc7c1a2241fa746b542c2e7"
        }
      ]
    }
  ]
}
