{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.3/compose-extension-1.0.3.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension.aar",
          "url": "compose-extension-android-1.0.3.aar",
          "size": 55279,
          "sha512": "fe546724cfa59452df473adf5bb237cd56bb87817134bab57b342c3442c363a1fd5fd366e7a416e071488e4560bd9b6cf3b873651e69637660d6f8bd17f08e62",
          "sha256": "c692779bbea93d36665cda60baaedea93478c32931b15cb8fbede80594fb3c53",
          "sha1": "579f04f814a5bfcfe70561cbfb18b86c192820d4",
          "md5": "a87077648ccca24c27b7925049801305"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension.aar",
          "url": "compose-extension-android-1.0.3.aar",
          "size": 55279,
          "sha512": "fe546724cfa59452df473adf5bb237cd56bb87817134bab57b342c3442c363a1fd5fd366e7a416e071488e4560bd9b6cf3b873651e69637660d6f8bd17f08e62",
          "sha256": "c692779bbea93d36665cda60baaedea93478c32931b15cb8fbede80594fb3c53",
          "sha1": "579f04f814a5bfcfe70561cbfb18b86c192820d4",
          "md5": "a87077648ccca24c27b7925049801305"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "compose-extension-android-1.0.3-sources.jar",
          "url": "compose-extension-android-1.0.3-sources.jar",
          "size": 19685,
          "sha512": "1a076224c37228563910597d7f7ce890a4e94d0a3a422ba714d07cd31bb9f0dbd604955491510bf152066fe5e4abc3994071b5d995712f56b234b35e1ae07158",
          "sha256": "2f5ea63fe6598de900caa7987d7b12d7af38ff2572dda806e742602f62b08101",
          "sha1": "05a72a0cdfd6e966da1bf2e028fc9f549b28e9be",
          "md5": "671b04dd65303192a8ca9849f773e699"
        }
      ]
    }
  ]
}
