{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.0.aar",
          "url": "ui-component-1.1.0.aar",
          "size": 131553,
          "sha512": "15728f163d5f017d8ac4307b5c7c915134e6b4de2fcadcbad9f0c8cbc33324bd7b9673631a2aba4aa611f331a3060fd668510d7b9cf76d931d8a66d9e9a6dd9a",
          "sha256": "adaa1a444d19a5f95d0f1b547840efc9d0d053a25c82bc1e043d6541256a6c6f",
          "sha1": "c607b8c0e08453690c080772796f131698191895",
          "md5": "c949eb1b867a596a03a7b82e8ed7c479"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.0.aar",
          "url": "ui-component-1.1.0.aar",
          "size": 131553,
          "sha512": "15728f163d5f017d8ac4307b5c7c915134e6b4de2fcadcbad9f0c8cbc33324bd7b9673631a2aba4aa611f331a3060fd668510d7b9cf76d931d8a66d9e9a6dd9a",
          "sha256": "adaa1a444d19a5f95d0f1b547840efc9d0d053a25c82bc1e043d6541256a6c6f",
          "sha1": "c607b8c0e08453690c080772796f131698191895",
          "md5": "c949eb1b867a596a03a7b82e8ed7c479"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.1.0-sources.jar",
          "url": "ui-component-1.1.0-sources.jar",
          "size": 44556,
          "sha512": "d5c4996584597793b000e41d0546fd7fb08e1b058295bea937046e206bdd715be48b09ba09343e21da8b623dba78d39f0191228b92893645287561bd082303d1",
          "sha256": "5e640a72550b2272aa3916b1d186c2f42455498d7d43ed0dfc8356eee75d49e9",
          "sha1": "db644a073d7c995531f9ceab957088574bd4a0f8",
          "md5": "af7550080b7846375c66034543079398"
        }
      ]
    }
  ]
}
