{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.3.aar",
          "url": "ui-component-1.1.3.aar",
          "size": 133147,
          "sha512": "500e570fb97ff2f83eeb5fb056dfbb1c76806bd33e44bf903e3caf74f994a29a8d549390f63bd95b84cff53db9b5f0706e7d6da9889d3fba9bc9e5c6e6be5c6a",
          "sha256": "0f4ac4fd867262a111ada573d53276f4c39215f0e5c630266caf3ae697e6c88b",
          "sha1": "f0c0ecae59539e4b3b7b1c5a14a5faf9c9e75371",
          "md5": "3ad54807489197d94b04c4304cef6f5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.3.aar",
          "url": "ui-component-1.1.3.aar",
          "size": 133147,
          "sha512": "500e570fb97ff2f83eeb5fb056dfbb1c76806bd33e44bf903e3caf74f994a29a8d549390f63bd95b84cff53db9b5f0706e7d6da9889d3fba9bc9e5c6e6be5c6a",
          "sha256": "0f4ac4fd867262a111ada573d53276f4c39215f0e5c630266caf3ae697e6c88b",
          "sha1": "f0c0ecae59539e4b3b7b1c5a14a5faf9c9e75371",
          "md5": "3ad54807489197d94b04c4304cef6f5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.1.3-sources.jar",
          "url": "ui-component-1.1.3-sources.jar",
          "size": 44556,
          "sha512": "96690cc8b12be0754cb3621396deb3b4c0b1a7b82c2454271b5f8cd124cb6543832907e138dab56ac68eb6e6a02e30a23a37a1f718ddad611d5924436397b3a3",
          "sha256": "a0fb511ab4f370f84c2d6c78cb232a6b7136d7ed0919ba9535abd049a02fc87e",
          "sha1": "31724afc40b837cec22a56c086b562960621e41e",
          "md5": "ca4dd0076659cd48d9dad7f2e27ce43f"
        }
      ]
    }
  ]
}
