{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.2.aar",
          "url": "ui-component-1.1.2.aar",
          "size": 131929,
          "sha512": "e6d5315b7b0e5b461125e56cd01dac01254424f5a15cb64f14f1d7306ab35e9ca86d18c14ce22a561699046f5fc2e2778fcf839c95d54e73487994e7e0c5bb40",
          "sha256": "a88e9d0ba0a8c094039e67c1786a7a7eab1ae99e621635f1b27239440274fab8",
          "sha1": "8350d44571e59436c19401675d3d877420790717",
          "md5": "b1d3692414e357ee340eaef546ce0ffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-1.1.2.aar",
          "url": "ui-component-1.1.2.aar",
          "size": 131929,
          "sha512": "e6d5315b7b0e5b461125e56cd01dac01254424f5a15cb64f14f1d7306ab35e9ca86d18c14ce22a561699046f5fc2e2778fcf839c95d54e73487994e7e0c5bb40",
          "sha256": "a88e9d0ba0a8c094039e67c1786a7a7eab1ae99e621635f1b27239440274fab8",
          "sha1": "8350d44571e59436c19401675d3d877420790717",
          "md5": "b1d3692414e357ee340eaef546ce0ffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-1.1.2-sources.jar",
          "url": "ui-component-1.1.2-sources.jar",
          "size": 44555,
          "sha512": "6fee6bf9255c53ba785b1e457c305d7aa178342da6e56cf6a0390df058a205e262db053780e5a198fbba93f4517a7ecfd3b1afaac9cbdddff6bc71583abff7ee",
          "sha256": "64decd72679db92572f1899b79a1206e6c4b921015162a7284027672d73eeef0",
          "sha1": "c95dd1b715be784dff1427994251e2f8ab6cf40d",
          "md5": "c6c384399d500587175a508193be3f79"
        }
      ]
    }
  ]
}
