{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-extension/1.0.3/compose-extension-1.0.3.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-desktop-1.0.3.jar",
          "url": "compose-extension-desktop-1.0.3.jar",
          "size": 57887,
          "sha512": "4b955d4cf7872e9198870fdca2c5197eb5b089a2451c9e931d17afe4fe971f484e112dd39caf1eb8ffa7e8c9d6c24a6106c4d49c47b1a7a805e66ee15946dbb7",
          "sha256": "355c5b20fa046dd02664c98744d536472ae6389c8d7ba33e3dc5781aea4d6fe2",
          "sha1": "ef2072bb48ef74ae2ef25062317135bf25d8669a",
          "md5": "b2a3fa6385cb4f89010bea330c622908"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-extension-desktop-1.0.3.jar",
          "url": "compose-extension-desktop-1.0.3.jar",
          "size": 57887,
          "sha512": "4b955d4cf7872e9198870fdca2c5197eb5b089a2451c9e931d17afe4fe971f484e112dd39caf1eb8ffa7e8c9d6c24a6106c4d49c47b1a7a805e66ee15946dbb7",
          "sha256": "355c5b20fa046dd02664c98744d536472ae6389c8d7ba33e3dc5781aea4d6fe2",
          "sha1": "ef2072bb48ef74ae2ef25062317135bf25d8669a",
          "md5": "b2a3fa6385cb4f89010bea330c622908"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compose-extension-desktop-1.0.3-sources.jar",
          "url": "compose-extension-desktop-1.0.3-sources.jar",
          "size": 20426,
          "sha512": "2107f43bb120b074191158c36dfc7ce1f498628a33c74912c68345c0122eaff3acfc96463518ede93607eb17a52efd6271d2e5c53ecdfb09f4203f5f3eb7b75f",
          "sha256": "2ec17273de9186ac2b919d04d64976b4506b03f6068d63e57442b80744e71d54",
          "sha1": "20867e8ef8ddf79f9110cfa01bb8c91069e16482",
          "md5": "76ac82d5584f00e886dfc396bf72bcb6"
        }
      ]
    }
  ]
}
