{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-multiplatform/0.1.1/compose-multiplatform-0.1.1.module",
    "group": "com.highcapable.betterandroid",
    "module": "compose-multiplatform",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-iosArm64Main-0.1.1.klib",
          "url": "compose-multiplatform-iosarm64-0.1.1.klib",
          "size": 84066,
          "sha512": "e39b9fb536584f7e288c5aecd46283961f41b60b2132a0b5133bf96335c00c15a24e0d4f9d017103b9281807b7cdf0164aef2cfafb99f5434eb60d5aeaf2b746",
          "sha256": "fc491f8ceb1d1925fd4d288df952fa0ff486ed722499b126c01c6f8b2e05fe8f",
          "sha1": "6dfecdc218dcf53866eb7d52f2c02a9e8fff45dd",
          "md5": "b67fea02340a4d96d392c24f9553bebf"
        },
        {
          "name": "compose-multiplatform-iosArm64Cinterop-uikitMain-0.1.1.klib",
          "url": "compose-multiplatform-iosarm64-0.1.1-cinterop-uikit.klib",
          "size": 8402,
          "sha512": "1f62901712347fe9f8dc165000ac8ad9e4b70dc3c3d89566cbd7283a398f44852cbf7caaae5908a76edd69656944dd571a03cafc6c822a427121d8875bf02f8c",
          "sha256": "ffa49321b194dfb4640ed3843453478af0fffe79e549d9982a4b57ee4e92ba2c",
          "sha1": "ebc6a9d362aeecf71d67d8d2d4c1ee190bcbe042",
          "md5": "8b907ca79e1ddb53cbb071a8d03c37a5"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-multiplatform-iosarm64-0.1.1-sources.jar",
          "url": "compose-multiplatform-iosarm64-0.1.1-sources.jar",
          "size": 25490,
          "sha512": "bc85249685679be988e802dcf52bf703d56a7625157842b3cfb2a2e3ac54d979e9af654057ae357b061e00018373fb9c8fc929aeaed2bd80cae17fa946aa6e8a",
          "sha256": "6c2545df71e1d10f98fde0b99e88b40bc02aeb168acb9425cc48b22ea638c356",
          "sha1": "6a17fb649ecb9f1e2c5dba0949a2ee85e5712a35",
          "md5": "81cefa5bc8eb6b6a18365ce870185c58"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-0.1.1.kotlin_resources.zip",
          "url": "compose-multiplatform-iosarm64-0.1.1-kotlin_resources.kotlin_resources.zip",
          "size": 390,
          "sha512": "ddec7467ea481e05441e2f7c6dff29971c1c85be8b901aab7521f8ce0659897c3a33d46320596b9f923c59674d75b10e319e0fd9086dcdbe40427e9df2c0c270",
          "sha256": "a6dc96c3c49dcb5197c49b0fc0c1d371a94739770fc5662b3ff8a9e19160dbca",
          "sha1": "c565b59399407c3d86d6a22cc75e3d30ad20e7f1",
          "md5": "1d93b517a5ac5a456d83f2782d023e8d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "compose-extension",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-multiplatform-iosarm64-0.1.1-metadata.jar",
          "url": "compose-multiplatform-iosarm64-0.1.1-metadata.jar",
          "size": 22961,
          "sha512": "53b638b953c8c3ce90a79d0cb0336263609bc72e31ced1d22b26866942429723ca0296828adb2b06537034564ce8aafacf643c9301362a2bee326a35b73b1546",
          "sha256": "f7c1d771a853845d33a4e24fecdd9f020da3bc0a73c1a94560e79deab97c1680",
          "sha1": "60b53e7677c8e13bffecf27645624833ffafd3d1",
          "md5": "36a7195652c497b36ccd39dc7b4fbec9"
        }
      ]
    }
  ]
}
