{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.kavaref",
    "module": "kavaref-extension",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kavaref-extension-1.0.3.jar",
          "url": "kavaref-extension-1.0.3.jar",
          "size": 35900,
          "sha512": "926d6643bbebf6bea4eb7d2c20544b62b1c2e7209b86580aa638f1f582f6e1bc0665cd36f936bad614064ebae06c527e12ed476b91221e16134bcfab0e2c8ea2",
          "sha256": "d0e4893daf95917a4b9d4c48152cb27c6f76d920ec0205e895ce6c82bcfbc22e",
          "sha1": "980b548864118bbd77d1471c594a15e951a39f20",
          "md5": "fbd950af9b92425fb366565f357e3315"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kavaref-extension-1.0.3.jar",
          "url": "kavaref-extension-1.0.3.jar",
          "size": 35900,
          "sha512": "926d6643bbebf6bea4eb7d2c20544b62b1c2e7209b86580aa638f1f582f6e1bc0665cd36f936bad614064ebae06c527e12ed476b91221e16134bcfab0e2c8ea2",
          "sha256": "d0e4893daf95917a4b9d4c48152cb27c6f76d920ec0205e895ce6c82bcfbc22e",
          "sha1": "980b548864118bbd77d1471c594a15e951a39f20",
          "md5": "fbd950af9b92425fb366565f357e3315"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kavaref-extension-1.0.3-sources.jar",
          "url": "kavaref-extension-1.0.3-sources.jar",
          "size": 12368,
          "sha512": "18fd8a1029466908924ed599c44488a0bca72175ed071cd32b6b5309ce5faad622c6f3a56e57a0ae97a460fb6e1552f19862deb6ef1865f84586cca78bd16a98",
          "sha256": "32a60828fad8a0e94ba4eb697e4c667675d45ac84b7503f54b2a90bf68bee2bf",
          "sha1": "cfe93eaafe46e446dc6b51c99981c41ec5e5113d",
          "md5": "ec97d66c9813d9b4bfd2f4ba624da3f7"
        },
        {
          "name": "kavaref-extension-1.0.3-sources.jar",
          "url": "kavaref-extension-1.0.3-sources.jar",
          "size": 12368,
          "sha512": "18fd8a1029466908924ed599c44488a0bca72175ed071cd32b6b5309ce5faad622c6f3a56e57a0ae97a460fb6e1552f19862deb6ef1865f84586cca78bd16a98",
          "sha256": "32a60828fad8a0e94ba4eb697e4c667675d45ac84b7503f54b2a90bf68bee2bf",
          "sha1": "cfe93eaafe46e446dc6b51c99981c41ec5e5113d",
          "md5": "ec97d66c9813d9b4bfd2f4ba624da3f7"
        }
      ]
    }
  ]
}
