{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.betterandroid",
    "module": "ui-component-adapter",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-adapter-1.1.4.aar",
          "url": "ui-component-adapter-1.1.4.aar",
          "size": 164874,
          "sha512": "25e50358de750c4c4b76f3e66d6142f660d9b988f24062b9dbbbc6ef6da1fd866666d16707fd81a08979fb4da7d027e7a3806c5fb55e95ce2a5a42cbb952827a",
          "sha256": "57e2e0a402fd7dfa5869c1a1f110d4d3af92f69cf5ef8854e737106bbdaf86d9",
          "sha1": "ceb3bf5bb1efaf78ae83c082bd562c8518025278",
          "md5": "c02c50fd80e427659f7861b48e557eb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-component-adapter-1.1.4.aar",
          "url": "ui-component-adapter-1.1.4.aar",
          "size": 164874,
          "sha512": "25e50358de750c4c4b76f3e66d6142f660d9b988f24062b9dbbbc6ef6da1fd866666d16707fd81a08979fb4da7d027e7a3806c5fb55e95ce2a5a42cbb952827a",
          "sha256": "57e2e0a402fd7dfa5869c1a1f110d4d3af92f69cf5ef8854e737106bbdaf86d9",
          "sha1": "ceb3bf5bb1efaf78ae83c082bd562c8518025278",
          "md5": "c02c50fd80e427659f7861b48e557eb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-component-adapter-1.1.4-sources.jar",
          "url": "ui-component-adapter-1.1.4-sources.jar",
          "size": 57624,
          "sha512": "a32f1e2476f60578cca5e879de4ae03687f0fee9dd8af1d591ab43e95e5c86fbcaa2f0ce849764a97768abbfe5a5128cac7e2dc352f17f993a6fb3199b7923c6",
          "sha256": "082ac7cf8d63c1c09bec76ef8ae90d640a368e68894ad6964da6d6bdef83e056",
          "sha1": "45b7e013b0778a745be24f5299c865e05cfe7d94",
          "md5": "2ae82bf3fb9d6abcec05082e1310965c"
        }
      ]
    }
  ]
}
